apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hoge-virtualservice
spec:
  hosts:
  - hoge.yokishava.dev
  gateways:
  - hoge-gateway
  http:
  - route:
    - destination:
        host: hoge-go
