apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoge-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoge-go
  template:
    metadata:
      labels:
        app: hoge-go
    spec:
      containers:
        - name: hoge-go
          image: gcr.io/wakashiyo-playground/hoge-go:0.0.2
          resources:
            limits:
              memory: "20Mi"
              cpu: "20m"
          ports:
            - containerPort: 80
