apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hoge-hpa
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hoge-go
  targetCPUUtilizationPercentage: 80
